Raya_Task/Controllers/Acounts/AccountsController.cs
using BLL.DTOs.Users;
using BLL.Extensions.Users;
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace RayaTaskMVC.Controllers.Acounts
{
    public class AccountsController : Controller
    {
        private readonly UserManager<User> _adminManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly SignInManager<User> _signInManager;

        public AccountsController(
            UserManager<User> adminManager,
            RoleManager<Role> roleManager,
            SignInManager<User> signInManager)
        {
            _adminManager = adminManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult LogIN()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIN([FromForm] LoginModel loginModel)
        {
            if (!ModelState.IsValid)
                return View(loginModel);
            try
            {

                var _user = await _adminManager.FindByNameAsync(loginModel.UserName);
                if(_user is null)
                 _user = await _adminManager.FindByEmailAsync(loginModel.UserName);


                if (_user is null || !await _adminManager.CheckPasswordAsync(_user, loginModel.Password))
                {
                    ModelState.AddModelError(string.Empty, "UserName or Password Is Incorrect!");
                    return View(loginModel);

                }
                var result = await _signInManager.PasswordSignInAsync(loginModel.UserName, loginModel.Password, true,true);
               
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(_user, loginModel.RememberMe);
                    return RedirectToAction("Index", "HRs");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login");
                    return View(loginModel);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(loginModel);
            }

        }
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([FromForm] RegistrationModel registrationModel)
        {
            if (!ModelState.IsValid)
                return View(registrationModel);
            try
            {
                if (await _adminManager.FindByEmailAsync(registrationModel.Email) != null)
                {
                    ModelState.AddModelError(string.Empty, "Email Is Already Registered!");
                    return View(registrationModel);
                }

                if (await _adminManager.FindByNameAsync(registrationModel.UserName) != null)
                {
                    ModelState.AddModelError(string.Empty, "UserName Is Already Registered!");
                    return View(registrationModel);
                }
                User _user = registrationModel.ToModel();
                var result = await _adminManager.CreateAsync(_user, registrationModel.Password);
                if (result.Succeeded)
                {
                    await _adminManager.AddToRoleAsync(_user, "HR");
                    //var token = await _adminManager.GenerateEmailConfirmationTokenAsync(_user);
                    //if (!string.IsNullOrEmpty(token))
                    //{
                    //    await SendEmailConfirmationEmail(_user, token);
                    //}
                    //return View(nameof(GOToEmailToConfirm));
                    //return View (registrationModel);

                    return RedirectToAction("Index", "HRs");

                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        //errors += $"{error.Description},";
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    return View(registrationModel);

                }


            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(registrationModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(LogIN));
        }

    }
}

Raya_Task/Controllers/Admin/UsersController.cs
using AutoMapper;
using BLL.DTOs.HRs;
using BLL.DTOs.Users;
using BLL.Enums.HRs;
using BLL.Services.HRs;
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq.Dynamic.Core;
using System.Text;

namespace Raya_Task.Controllers.Admin
{
    //[Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly IMapper _mapper;
        public UsersController(
            UserManager<User> userManager,
            RoleManager<Role> roleManager,
            IMapper mapper)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetAllUsers()
        {
            var pageSize = int.Parse(Request.Form["length"]);
            var skip = int.Parse(Request.Form["start"]);

            var searchValue = Request.Form["search[value]"];

            var sortColumn = Request.Form[string.Concat("columns[", Request.Form["order[0][column]"], "][name]")];
            var sortColumnDirection = Request.Form["order[0][dir]"];


            IQueryable<UserDTO> users = _userManager.Users.Select(u => new UserDTO
            {
                Id = u.Id,
                Email = u.Email,
                FirstName = u.FirstName,
                LastName = u.LastName,
                UserName = u.UserName

            })
              .Where(m => string.IsNullOrEmpty(searchValue) ? true :
              m.FirstName.Contains(searchValue) ||
              m.LastName.Contains(searchValue) ||
              m.UserName.Contains(searchValue) ||
              m.Email.Contains(searchValue));

            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                users = users.OrderBy(string.Concat(sortColumn, " ", sortColumnDirection));



            var data = users.Skip(skip).Take(pageSize).ToList();

            var recordsTotal = users.Count();

            var jsonData = new { recordsFiltered = recordsTotal, recordsTotal, data };

            return Ok(jsonData);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserDTO userDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(userDTO);
            }
            try
            {
                ViewBag.Roles = new SelectList(_roleManager.Roles, "Id", "Name");

                if (await _userManager.FindByEmailAsync(userDTO.Email) is not null)
                {
                    ModelState.AddModelError(string.Empty, "Email Is Already Registered!");
                    return View(userDTO);
                }

                if (await _userManager.FindByNameAsync(userDTO.UserName) is not null)
                {
                    ModelState.AddModelError(string.Empty, "UserName Is Already Registered!");
                    return View(userDTO);
                }
                User _user = _mapper.Map<User>(userDTO);
                var result = await _userManager.CreateAsync(_user, userDTO.Password);
                if (result.Succeeded)
                {
                    if (userDTO.RoleIds is not null)
                    {
                        IEnumerable<string> roles = _roleManager.Roles.Where(x => userDTO.RoleIds.Contains(x.Id)).Select(n => n.Name).ToList();
                        var userCreated = await _userManager.FindByEmailAsync(_user.Email);
                        var result2 = await _userManager.AddToRolesAsync(userCreated, roles);
                        if (result2.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            foreach (var error in result2.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }

                            return View(userDTO);
                        }
                    }



                    return RedirectToAction("Index");

                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        //errors += $"{error.Description},";
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    return View(userDTO);

                }


            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(userDTO);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return View(id);
            }
            try
            {
                var result = await _userManager.FindByIdAsync(id.ToString());
                if (result is not null)
                {
                    var result2 = await _userManager.DeleteAsync(result);
                    if (result2.Succeeded)
                    {
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        var errors = new StringBuilder();
                        foreach (var item in result2.Errors)
                        {
                            errors.Append($"{item.Description} , ");
                        }
                        throw new Exception(errors.ToString());

                    }
                }
                else
                    return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }

        public async Task<IActionResult> Details(int id)
        {
            if (!ModelState.IsValid)
            {
                return View(id);
            }
            try
            {
                var user = await _userManager.FindByIdAsync(id.ToString());
                if (user is not null)
                {

                    return View(new DetailsUserDTO
                    {
                        Id = user.Id,
                        UserName = user.UserName,
                        Email = user.Email,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        RoleNames = await _userManager.GetRolesAsync(user)
                    });
                }

                else
                    return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name", "Name");

            if (!ModelState.IsValid)
            {
                return View(id);
            }
          
            try
            {
               

                var user = await _userManager.FindByIdAsync(id.ToString());
                if(user is not null)
                {
                    return View(new DetailsUserDTO
                    {
                        Id = user.Id,
                        UserName = user.UserName,
                        Email = user.Email,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        RoleNames = await _userManager.GetRolesAsync(user)
                    });

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "UserName Is Already Registered!");
                    return View(id);

                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }
            

        }

        [HttpPost]
        public async Task<IActionResult> Edit(DetailsUserDTO model)
        {
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name", "Name");

            if (!ModelState.IsValid )
            {
               return View(model);
            }
            try
            {
              
                //if (await _userManager.FindByEmailAsync(model.Email) is not null)
                //{
                //    ModelState.AddModelError(string.Empty, "email is already found!");
                //    return View(model);
                //}



                var user = await _userManager.FindByIdAsync(model.Id.ToString());
                if (user is not null)
                {
                    user.UserName = model.UserName;
                    user.Email = model.Email;
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    await _userManager.RemoveFromRolesAsync(user, _userManager.GetRolesAsync(user).Result);
                    var resultRole=await _userManager.AddToRolesAsync(user,model.RoleNames??new List<string>()) ;
                    var resultUpdated=await _userManager.UpdateAsync(user);
                    if (resultUpdated.Succeeded )
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {

Raya_Task/Views/Shared/_Layout.cshtml
@using DAL.Models;
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RayaTask</title>

<!-- Favicons -->
    @*<link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
*@
    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">@*
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">*@
    <script src="https://kit.fontawesome.com/adc5c6a0d2.js" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- fontawesome-->
    @*<link href="~/assets/fontawesome-free/css/all.min.css" rel="stylesheet">*@

    <script src="https://kit.fontawesome.com/adc5c6a0d2.js" crossorigin="anonymous"></script>
    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    @*Change style on site *@
    <link href="~/css/site.css" asp-append-version="true" rel="stylesheet">

</head>
<body>
  
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex justify-content-between">

        <div class="d-flex align-items-center justify-content-between">
            <a asp-action="Index" asp-controller="Home" class="logo d-flex align-items-center">

                <span class="d-none d-lg-block">Raya Task</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->
        
        <nav class="nav justify-content-center  fs-5">
            <a class="nav-link text-dark fw-light" asp-action="Index" asp-controller="Home" aria-current="page">Home</a>
         
            <a class="nav-link text-dark fw-light" asp-action="Index" asp-controller="Hrs">Employee</a>
            <a class="nav-link text-dark fw-light" asp-action="Index" asp-controller="Users">User</a>
        </nav>
       

        <div class="dropdown p-2">
            <button class="btn btn-secondary dropdown-toggle rounded-pill" type="button"
                    id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Hello , @User.Identity?.Name


            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                @if (string.IsNullOrEmpty(@User.Identity.Name))
                {
                    <li><a class="dropdown-item" asp-action="LogIN" asp-controller="Accounts">SignIn</a></li>
                    <li><a class="dropdown-item" asp-action="SignUp" asp-controller="Accounts">SignUp</a></li>

                }
                <li><a class="dropdown-item" asp-action="LogOut" asp-controller="Accounts">LogOut</a></li>
            </ul>
        </div>

        
    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar " style="background-color:#3C4B64">


        <ul class="sidebar-nav" id="sidebar-nav">
            <!-- start Dashboard Nav -->
            <li class="nav-item">
                <a style="background-color:#303C54;color:white;border-radius:25px" class="nav-link " asp-action="Index" asp-controller="Home">
                    <i style="color:white" class="bi bi-grid mx-2"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- End Dashboard Nav -->

           

            <!-- start Employee Nav -->
            <li class="nav-item" style="background-color:#303C54;color:white;border-radius:25px">
                <a style="background-color:#303C54;color:white;border-radius:25px" class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                    <i style="color:white" class="fas fa-user-tie fa-lg mx-2 "></i><span>Employee</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="HRs" asp-action="Index">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>All Employee</span>
                        </a>
                    </li>
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="HRs" asp-action="Create">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>Create New Employee</span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- End Employee Nav -->
            <!-- start Role Nav -->
            <li class="nav-item" style="background-color:#303C54;color:white;border-radius:25px">
                <a style="background-color:#303C54;color:white;border-radius:25px" class="nav-link collapsed" data-bs-target="#Roles-nav" data-bs-toggle="collapse" href="#">
                    <i style="color:white" class="fa-solid fa-gears mx-2 "></i><span>Roles</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="Roles-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="Roles" asp-action="Index">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>All Roles</span>
                        </a>
                    </li>
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="Roles" asp-action="Create">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>Create New Roles</span>
                        </a>
                    </li>
                   
                </ul>
            </li>
            <!-- End user Nav -->
            <!-- start user Nav -->
            <li class="nav-item" style="background-color:#303C54;color:white;border-radius:25px">
                <a style="background-color:#303C54;color:white;border-radius:25px" class="nav-link collapsed" data-bs-target="#Users-nav" data-bs-toggle="collapse" href="#">
                    <i style="color:white" class="fas fa-users mx-2 "></i><span>User</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="Users-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="Users" asp-action="Index">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>All Users</span>
                        </a>
                    </li>
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="Users" asp-action="Create">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>Create New User</span>
                        </a>
                    </li>
                    <li>
                        <a style="background-color:#303C54;color:white;border-radius:25px" asp-controller="Users" asp-action="AddRole">
                            <i style="color:white" class="bi bi-circle mx-2"></i><span>Add Role For User</span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- End user Nav -->

        

        </ul>

    </aside>
    <!-- End Sidebar-->


    <main id="main" class="main" style="min-height:570px;background-color:#F0F1F3">

        @RenderBody()

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->

    @*///*@
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a class="text-dark fw-bold fst-italic" href="mailto:salh.15237657@compit.au.edu.eg">salh.15237657@compit.au.edu.eg</a>

        </div>
    </footer><!-- End Footer -->
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
  
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <!-- icon CDN-->
    <script src="https://unpkg.com/ionicons@latest/dist/ionicons.js"></script>

   

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Raya_Task/Views/Shared/_SweetalertScriptsPartial.cshtml
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>